name: stop_smog
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cached_network_image: ^1.1.1
  video_player: ^0.10.2+3
  youtube_player: ^3.5.0
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  charts_flutter: ^0.8.1
  random_color: ^1.0.3
  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0+8
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  fcharts: ^0.0.11
  firebase_auth: ^0.15.0+1
  shared_preferences: ^0.5.4+6
  flushbar: ^1.9.1
  google_maps_flutter: ^0.5.21+12
  flare_flutter: any
  mono_kit: any
  simple_logger: ^1.5.1+1
  url_launcher: any
  rxdart: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  syncfusion_flutter_charts: ^17.3.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.1.4
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: "^0.7.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/pl.json
    - assets/info1.png
    - assets/info2.png
    - assets/info3.png
    - assets/logo.png
    - assets/back0.png
    - assets/back1.png
    - assets/back2.png
    - assets/back3.png
    - assets/back4.png
    - assets/back5.png
    - assets/animation/
    - assets/data/
    - assets/info/
    - assets/info/000.png
    - assets/info/001.png
    - assets/info/002.png
    - assets/info/003.png
    - assets/info/004.png
    - assets/info/005.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Regular.ttf
        - asset: assets/fonts/Bitter-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open Sans-Regular.ttf
        - asset: assets/fonts/Open Sans-Italic.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true