
import 'package:stop_smog/Blog/Models/Post.dart';

// zrobić odczyt z bazy

const SampleDataBlog = const [
  Post(
    id: 1, 
    title:'Artykuł 1', 
    author: 'Grzegorz Wojnarowski', 
    content: "Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.",
    keyWords: ["Sport","Siatkowka","Zdrowie"],
    imageUrl: 'https://ozonemask.pl/wp-content/uploads/2018/10/Zrzut-ekranu-2018-10-14-o-15.20.16-1170x662.png'
  ),

  Post(
    id: 2, 
    title:'Artykuł 2', 
    author: 'Marek Matacz',
    content: "Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.",
    keyWords: ["Smog","Zdrowie"],
    imageUrl: 'https://s9.dziennik.pl/pliki/9769000/9769173-smog-w-miescie-900-555.jpg'
  ),

    Post(
    id: 3, 
    title:'Artykuł 3', 
    author: 'Jan Nowak',
    content: "Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.",
    keyWords: ["Bank","Ekonomia"],
    imageUrl: 'https://ozonemask.pl/wp-content/uploads/2018/10/Zrzut-ekranu-2018-10-14-o-15.20.16-1170x662.png'
  ),

    Post(
    id: 4, 
    title:'Artykuł 4', 
    author: 'Grzegorz Wojnarowski',
    content: "Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.",
    keyWords: ["Technologia","Ekonomia"],
    imageUrl: 'https://www.kobieta.pl/uploads/media/default/0002/11/69d8cd34d5bf6e00956db0804a3bba7e396e68fe.jpeg'
  ),

    Post(
    id: 5, 
    title:'Artykuł 5', 
    author: 'Hanna Gadomska',
    content: "Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.Po trzech meczach w wielkiej hali w Rotterdamie na kolejne dwa spotkania Biało-Czerwoni przenieśli się do holenderskiej stolicy. Do większego miasta, ale obiektu, który przy Ahoy Arenie wygląda jak łupina pana Maluśkiewicza przy transatlantyku. W zaledwie 2,5 tysięcznej Sporthallen Zuid siłą rzeczy było też mniej polskich kibiców - ci wypełnili trybuny mniej więcej w dwóch trzecich. Amsterdam i okolice zamieszkuje podobno mniej naszych rodaków, a powód jest prosty - życie jest tu zdecydowanie droższe. Bilety na spotkanie z Czarnogórą drogie jednak nie były - te na wtorkowy mecz piłkarskiej Ligi Mistrzów pomiędzy Ajaksem a francuskim Lille kosztują ponoć 20 razy więcej - a patrząc na grę swojej siatkarskiej reprezentacji polscy fani mogli poczuć się jak bogacze, którym inni zazdroszczą fortuny.",
    keyWords: ["Jedzenie ","Zdrowie"],
    imageUrl: 'https://airly.eu/static/c093583ba2cf3974c3deee3b4c8ee02e/14dee/smog-definicja-skutki-i-przyczyny-1.jpg'
  ),
  
];